# cloudbuild.yaml
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
  # 1) Build the container
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - build
      - -t
      - us-west1-docker.pkg.dev/cs144-25s-team23/flashmind/flashmind-full:$SHORT_SHA
      - .

  # 2) Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - push
      - us-west1-docker.pkg.dev/cs144-25s-team23/flashmind/flashmind-full:$SHORT_SHA

  # 3) Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=flashmind-cluster'
    args:
      - apply
      - -f
      - kubernetes/

# Let Cloud Build know this image was built, for automatic garbage collection etc.
images:
  - us-west1-docker.pkg.dev/cs144-25s-team23/flashmind/flashmind-full:$SHORT_SHA
