name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  gke-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'deploy with gke-deploy cli'
      uses: 'google-github-actions/deploy-gke-container@v0.1'
      with:
        image: 'us-west1-docker.pkg.dev/cs144-25s-team23/flashmind/flashmind-full:latest'
        app_name: 'flashmind'
        region: 'us-west1'
        cluster_name: 'flashmind-cluster'
        project_id: 'cs144-25s-team23'
        namespace: 'default'
        k8s_manifests: 'kubernetes'
    
    - name: 'get-deployments'
      shell: bash
      run: |
        kubectl get pods -n default
        kubectl get deployment -n default