on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-to-gke:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'

      - name: Deploy with gke-deploy CLI
        uses: google-github-actions/deploy-gke-container@v0.1
        with:
          image:        us-west1-docker.pkg.dev/cs144-25s-team23/flashmind/flashmind-full:latest
          app_name:     flashmind
          region:       us-west1
          cluster_name: flashmind-cluster
          project_id:   cs144-25s-team23
          namespace:    my-namespace
          expose:       '8000'
          k8s_manifests: configs

      - name: Verify deployment
        run: |
          kubectl get pods       -n my-namespace
          kubectl get deployment -n my-namespace
