name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  gke-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: cs144-25s-team23
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

    - name: Deploy GKE
      uses: google-github-actions/deploy-gke@v0.0.3
      with:
        image: 'us-west1-docker.pkg.dev/cs144-25s-team23/flashmind/flashmind-full:latest'
        app_name: 'flashmind'
        region: 'us-west1'
        cluster_name: 'flashmind-cluster'
        project_id: 'cs144-25s-team23'
        namespace: 'default'
    
    - name: 'get-deployments'
      shell: bash
      run: |
        kubectl get pods -n default
        kubectl get deployment -n default